version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: disabled
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"